### PR TITLE
feat(index): compute from meta

### PR DESCRIPTION
**Pull request by kptdobe**
Update index based on latest content structure and extract from metadata.

@dominique-pfister Is there a way to test the result of this new index definition on some files ?

### CODE REVIEW

**Comment by dominique-pfister** [comment]
> @dominique-pfister Is there a way to test the result of this new index definition on some files ?

Yes: you can invoke the runtime action `helix-index-files` for a document `/the/path/to/index.docx` as follows:

```
wsk action invoke -r \
  -p owner adobe \
  -p repo spark-website \
  -p ref blog-index \
  -p path /the/path/to/index.docx
```

**Review by dominique-pfister — APPROVED** [review]
Looks much simpler, nice!

**Review by dominique-pfister — APPROVED** [review]

**Comment by kptdobe** [comment]
Thanks @dominique-pfister (I think I already asked you multiple times ;) ).

For record, the correct testing command is: 

```
wsk action invoke /helix/helix-observation/index-pipelines@latest -r \
  -p owner adobe \
  -p repo spark-website \
  -p ref blog-index \
  -p path /the/path/to/index.html
```

Version was missing for me.

**Comment by kptdobe** [comment]
The indexing looks correct now except for the tags which requires https://github.com/adobe/helix-pages/issues/806.

**Comment by dominique-pfister** [comment]
> Version was missing for me.

Right, sorry about that!

**Pull request merged**
