### PR TITLE
feat(template-list): optional 4 column layout

### PR DESCRIPTION
**Pull request by rofe**
Fix https://github.com/adobe/spark-website-issues/issues/21

### CODE REVIEW

**Review by kptdobe — APPROVED** [review]

**Comment by rofe** [comment]
Really weird: looking at https://github.com/adobe/spark-website/commits/main/express/blocks/template-list/template-list.css, it seems like the changes from this PR never actually arrived in `main`. As if someone hard-reset the main branch to an earlier commit...

@kptdobe wdyt happened?

**Comment by rofe** [comment]
Weirder still: https://github.com/adobe/spark-website/compare/issue-21 shows no difference between this branch and `main`!

**Comment by kptdobe** [comment]
This is pretty mysterious... the commit shows that it did something in `main` but no trace of the change in the file history... really weird!

**Comment by rofe** [comment]
Thank you! I thought I was losing my mind 😜

**Pull request merged**
